# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52bd8b188641830867177adaa250c797477d766b87ece6a68ba3e32d96453c486f7e45ae088b37894bb5cb0a570578a8f9061d7166e0b400795b0088ee5e2be7
  gmail_username: '21.francisco.gonzalez@gmail.com'
  gmail_password: '76205.dariojara'

test:
  secret_key_base: 69de4c36647aa962bfd79abe1a6878a994dad2be5ff0575e6ca2009e6353ac44ba0d56e68b262554e55b300f94f2ae73cd68e53554066d2b6b12c320ceca5589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 69de4c36647aa962bfd79abe1a6878a994dad2be5ff0575e6ca2009e6353ac44ba0d56e68b262554e55b300f94f2ae73cd68e53554066d2b6b12c320ceca5589
  gmail_username: '21.francisco.gonzalez@gmail.com'
  gmail_password: '76205.dariojara'
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
